# Generated by Django 2.0.2 on 2019-12-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_orders',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
