# Generated by Django 2.0.2 on 2020-01-08 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_user_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_orders',
        ),
    ]
